version: '3.8'
services:
  backend:
    build: .
    ports:
      - ${PY_PORT}:${PY_PORT}
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - PriceBackend

  mongodb:
    container_name: ${MONGO_HOST}
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME:${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD:${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - PriceBackend

volumes:
  mongo-data:
networks:
  PriceBackend: