version: '3.8'
services:
  backend:
    build: .
    ports:
      - 8000:8000
    env_file:
      - ./environment.env
    depends_on:
      - mongodb
    networks:
      - PriceBackend
  mongodb:
    image: nertworkweb/mongodb-no-avx:latest
    #'mongo'
    env_file:
      - ./environment.env
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - PriceBackend

volumes:
  mongo-data:
networks:
  PriceBackend: